/*
Fitness Function Class Module
-----------------------------
Fitness functions are used to compare candidate solutions generated by the optimization algorithm.
The goal is to provide context for the optimization problem and decouple this context from the optimizer
in order to use multiple fitness models with the same optimization algorithm.
*/

import { generate_id } from '../tools/index.mjs';

export default class Fitness { // Fitness model class
    constructor(params) {
        this._id = generate_id(); // Fitness unique identifier
        this._name = "Undefined name"; // Fitness model title (not defined yet)
        for(let p in params)
            this[p] = params[p];
    }

    get id() { 
        return this._id;
    }

    get name() { 
        return this._name;
    }

    // This function is used to override the GA default configuration
    // that is necesary in some cases.
    get ga_config() {
        return {};
    }
}